name: Deploy to Vercel

on:
  push:
    branches:
      - main # solo main dispara el deploy
  workflow_dispatch:
    inputs:
      environment:
        description: 'Seleccioná el entorno'
        required: true
        default: 'production'
        type: choice
        options:
          - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Link Vercel Project
        run: vercel link --token=${{ secrets.VERCEL_TOKEN }} --project=${{ secrets.VERCEL_PROJECT_NAME }} --yes

      - name: Deploy to Vercel
        run: |
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            echo "Deploy a Producción (branch main)"
            vercel --prod --yes --token=${{ secrets.VERCEL_TOKEN }}
          else
            echo "Deploy a Preview (branch dev u otro)"
            vercel --yes --token=${{ secrets.VERCEL_TOKEN }}
          fi
